#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 24, 2020 09:26:46 PM IST  platform: Windows NT

import sys
from tkinter import messagebox
import os
from subprocess import call
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support
import sqlite3 as sql

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def userlogin(self):
        name=self.username.get()
        pwd=self.password.get()
        cnx = sql.connect('project.sqlite')
        c=cnx.cursor()
        c.execute("""SELECT * FROM login where username=? and password=?""",(name,pwd))
        result=c.fetchone()
        if result:
            call(["python", "home.py"])
        else:
            messagebox.showerror("Error","Please Login with correct credential")
        cnx.close()
        

        
    def __init__(self, top=None):
        _bgcolor ='#d9d9d9'  # X11 color: 'gray85'
        _fgcolor ='#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("623x475+450+150")
        top.minsize(160, 1)
        top.maxsize(1924, 1055)
        top.resizable(0, 0)
        top.title("Login Page")
        top.configure(background="#9211a6")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.login = tk.Button(top)
        self.login.place(relx=0.161, rely=0.589, height=35, width=120)
        self.login.configure(activebackground="#ececec")
        self.login.configure(activeforeground="#ffffff")
        self.login.configure(background="#400080")
        self.login.configure(borderwidth="5")
        self.login.configure(disabledforeground="#a3a3a3")
        self.login.configure(foreground="#ffffff")
        self.login.configure(highlightbackground="#d9d9d9")
        self.login.configure(highlightcolor="black")
        self.login.configure(padx="0")
        self.login.configure(pady="0")
        self.login.configure(text='''Login''')
        self.login.configure(command=self.userlogin)

        self.l = tk.Label(top)
        self.l.place(relx=0.353, rely=0.084, height=26, width=172)
        self.l.configure(activebackground="#f9f9f9")
        self.l.configure(activeforeground="black")
        self.l.configure(background="#9211a6")
        self.l.configure(disabledforeground="#a3a3a3")
        self.l.configure(font="-family {Segoe UI Black} -size 14 -weight bold -underline 1")
        self.l.configure(foreground="#ffffff")
        self.l.configure(highlightbackground="#d9d9d9")
        self.l.configure(highlightcolor="black")
        self.l.configure(text='''LOGIN PAGE''')

        self.lblpass = tk.Label(top)
        self.lblpass.place(relx=0.161, rely=0.4, height=26, width=92)
        self.lblpass.configure(activebackground="#ffffff")
        self.lblpass.configure(activeforeground="#ffffff")
        self.lblpass.configure(anchor='sw')
        self.lblpass.configure(background="#9211a6")
        self.lblpass.configure(disabledforeground="#a3a3a3")
        self.lblpass.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblpass.configure(foreground="#ffffff")
        self.lblpass.configure(highlightbackground="#d9d9d9")
        self.lblpass.configure(highlightcolor="black")
        self.lblpass.configure(justify='left')
        self.lblpass.configure(text='''Password''')

        self.lblpass_3 = tk.Label(top)
        self.lblpass_3.place(relx=0.161, rely=0.232, height=26, width=93)
        self.lblpass_3.configure(activebackground="#ffffff")
        self.lblpass_3.configure(activeforeground="#ffffff")
        self.lblpass_3.configure(anchor='sw')
        self.lblpass_3.configure(background="#9211a6")
        self.lblpass_3.configure(disabledforeground="#a3a3a3")
        self.lblpass_3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.lblpass_3.configure(foreground="#ffffff")
        self.lblpass_3.configure(highlightbackground="#d9d9d9")
        self.lblpass_3.configure(highlightcolor="black")
        self.lblpass_3.configure(justify='left')
        self.lblpass_3.configure(text='''Username''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.username = tk.Entry(top)
        self.username.place(relx=0.161, rely=0.295,height=30, relwidth=0.697)
        self.username.configure(background="white")
        self.username.configure(disabledforeground="#a3a3a3")
        self.username.configure(font="TkFixedFont")
        self.username.configure(foreground="#000000")
        self.username.configure(highlightbackground="#d9d9d9")
        self.username.configure(highlightcolor="black")
        self.username.configure(insertbackground="black")
        self.username.configure(selectbackground="#c4c4c4")
        self.username.configure(selectforeground="black")

        self.password = tk.Entry(top)
        self.password.place(relx=0.161, rely=0.463,height=30, relwidth=0.697)
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="#c4c4c4")
        self.password.configure(selectforeground="black")
        self.password.configure(show="*")

if __name__ == '__main__':
    vp_start_gui()
    




